import { SyllabusItem } from "../types";

export const INITIAL_SYLLABUS: SyllabusItem[] = [
  // --- PHYSICS ---
  {
    id: "phy-1",
    subject: "Physics",
    chapterName: "Units, Dimensions & Errors",
    category: "Mains",
    status: "Completed",
    lecturesWatched: 2,
    totalLectures: 3,
    dppDone: true,
    hwDone: true,
    notesRevised: true,
    totalQuestions: 40,
    pyqsSolved: 20,
  },
  {
    id: "phy-2",
    subject: "Physics",
    chapterName: "Kinematics (1D & 2D)",
    category: "Both",
    status: "In Progress",
    lecturesWatched: 6,
    totalLectures: 8,
    dppDone: true,
    hwDone: false,
    notesRevised: true,
    totalQuestions: 80,
    pyqsSolved: 35,
  },
  {
    id: "phy-3",
    subject: "Physics",
    chapterName: "Newton's Laws of Motion & Friction",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 10,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "phy-4",
    subject: "Physics",
    chapterName: "Work, Power & Energy",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 7,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "phy-5",
    subject: "Physics",
    chapterName: "Rotational Motion & Inertia",
    category: "Advanced",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 12,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "phy-6",
    subject: "Physics",
    chapterName: "Electrostatics & Gauss Law",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 14,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "phy-7",
    subject: "Physics",
    chapterName: "Current Electricity",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 10,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "phy-8",
    subject: "Physics",
    chapterName: "Modern Physics (Dual Nature, Atoms, Nuclei)",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 12,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },

  // --- CHEMISTRY ---
  {
    id: "chem-1",
    subject: "Chemistry",
    chapterName: "Some Basic Concepts of Chemistry (Mole Concept)",
    category: "Mains",
    status: "Completed",
    lecturesWatched: 5,
    totalLectures: 5,
    dppDone: true,
    hwDone: true,
    notesRevised: true,
    totalQuestions: 90,
    pyqsSolved: 50,
  },
  {
    id: "chem-2",
    subject: "Chemistry",
    chapterName: "Atomic Structure",
    category: "Both",
    status: "In Progress",
    lecturesWatched: 4,
    totalLectures: 7,
    dppDone: true,
    hwDone: true,
    notesRevised: false,
    totalQuestions: 50,
    pyqsSolved: 15,
  },
  {
    id: "chem-3",
    subject: "Chemistry",
    chapterName: "Chemical Bonding & Molecular Structure",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 10,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "chem-4",
    subject: "Chemistry",
    chapterName: "Chemical Kinetics & Equilibrium",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 9,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "chem-5",
    subject: "Chemistry",
    chapterName: "General Organic Chemistry (GOC)",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 15,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "chem-6",
    subject: "Chemistry",
    chapterName: "Coordination Compounds",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 8,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },

  // --- MATHEMATICS ---
  {
    id: "math-1",
    subject: "Mathematics",
    chapterName: "Sets, Relations, & Functions",
    category: "Mains",
    status: "Completed",
    lecturesWatched: 4,
    totalLectures: 4,
    dppDone: true,
    hwDone: true,
    notesRevised: true,
    totalQuestions: 60,
    pyqsSolved: 40,
  },
  {
    id: "math-2",
    subject: "Mathematics",
    chapterName: "Quadratic Equations & Complex Numbers",
    category: "Both",
    status: "In Progress",
    lecturesWatched: 5,
    totalLectures: 9,
    dppDone: true,
    hwDone: false,
    notesRevised: true,
    totalQuestions: 75,
    pyqsSolved: 30,
  },
  {
    id: "math-3",
    subject: "Mathematics",
    chapterName: "Matrices & Determinants",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 8,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "math-4",
    subject: "Mathematics",
    chapterName: "Limits, Continuity & Differentiability",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 12,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "math-5",
    subject: "Mathematics",
    chapterName: "Definite & Indefinite Integration",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 14,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "math-6",
    subject: "Mathematics",
    chapterName: "Probability & Permutations",
    category: "Advanced",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 11,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
  {
    id: "math-7",
    subject: "Mathematics",
    chapterName: "Vectors & 3D Geometry",
    category: "Both",
    status: "Not Started",
    lecturesWatched: 0,
    totalLectures: 10,
    dppDone: false,
    hwDone: false,
    notesRevised: false,
    totalQuestions: 0,
    pyqsSolved: 0,
  },
];
